[package]
name = "snaptokens-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
serde_json = "1.0"
arbitrary = { version = "1", features = ["derive"] }

[dependencies.snaptokens]
path = ".."

[[bin]]
name = "fuzz_json_parse"
path = "fuzz_targets/fuzz_json_parse.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_encode"
path = "fuzz_targets/fuzz_encode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_decode"
path = "fuzz_targets/fuzz_decode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_tkz"
path = "fuzz_targets/fuzz_tkz.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_roundtrip"
path = "fuzz_targets/fuzz_roundtrip.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_unigram"
path = "fuzz_targets/fuzz_unigram.rs"
test = false
doc = false
bench = false
