[package]
name = "snaptokens-benchmark"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
anyhow = "1"
fastokens-upstream = { package = "fastokens", git = "https://github.com/crusoecloud/fastokens", rev = "326cb5afc5a033d2f7885832d12fd43b9ea50cdd" }
gigatoken_rs = { package = "gigatoken", git = "https://github.com/marcelroed/gigatoken", rev = "e6564f3ad3364e58ff02b2b251a96b518b6eaaa2", default-features = false }
iree-tokenizer = { git = "https://github.com/iree-org/iree-tokenizer-rust", rev = "c1537a9612e73a40626d1f58062090d71849fe35" }
kitoken = { git = "https://github.com/Systemcluster/kitoken", rev = "5e9ed29631502471355db8b30e7fe9ac05ea64e1" }
libloading = "0.8"
rayon = "1.11"
serde_json = "1"
snaptokens = { path = "../.." }
splintr = { git = "https://github.com/ml-rust/splintr", rev = "67d71b70eaca839cb1b1e6f43132252d27b74f96" }
tokie = { git = "https://github.com/chonkie-inc/tokie", rev = "9b78cc552df73c0fa41451c51e08fe94638fa48c" }
tokenizers = { git = "https://github.com/huggingface/tokenizers", rev = "b62132e4e0ec7518caba201408a680819dfdcd22" }

[profile.release]
codegen-units = 1
lto = "thin"
