[alias]
bench-load = "bench --manifest-path benchmarks/tools/Cargo.toml --bench load_bench --"
bench-pipeline = "bench --manifest-path benchmarks/tools/Cargo.toml --bench print_pipeline --"
bench-sample = "bench --manifest-path benchmarks/tools/Cargo.toml --bench profile_sample --"
bench-simple = "bench --manifest-path benchmarks/tools/Cargo.toml --bench simple_bench --"
